### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by baimafeima** [rime/ibus-rime#19]
Is this still actively maintained? It hasn't seen a new release since July 19, 2014. Please advise whether you are planning to release new versions. Thank you. 

Solus is currently implementing and testing Ibus and it would be great to have an alternative to ibus-libpinyin: https://solus-project.com/

Ibus-rime was rejected due to not having seen any commits in over a year. You can track progress on the Solus dev tracker here: https://dev.solus-project.com/T1001

**Comment by lotem** [comment]
It's not actively maintained, no.
I don't see a need to update this package in the near future, because *ibus-rime* only serves as a thin wrapper around *librime* which implements the underlying input logic and is more actively developed by a number of collaborators. (Though it too hasn't had a *tagged* release for a while.)
Future releases of ibus-rime is expected to be less often as long as we don't make breaking changes in librime's API, and there's no new UI features.

**Comment by baimafeima** [comment]
Thanks for the reply and good to know that ibus-rime is still maintained when necessary, albeit less frequently.

**Comment by lotem** [comment]
Let's close this issue for now and revisit when a new release arrives.
