### ISSUE TITLE
Cannot get ibus_rime.yaml to work

### ISSUE THREAD

**Issue by DreaminginCodeZH** [rime/ibus-rime#42]
I've read the changelog of v1.3.0 and c8492d723860f5363d4e9364f0f6df745d59d219 plus some code in librime, however I'm still unable to set my `style/horizontal` to `true`.

My ibus-setup UI (Don't know why `IBUS_ORIENTATION_SYSTEM` isn't working):

![2018-04-25 13-32-40](https://user-images.githubusercontent.com/4469895/39271190-259570e2-488d-11e8-8106-1bfa56a47a71.png)

My dconf showing the orientation setting:

![2018-04-25 13-33-03](https://user-images.githubusercontent.com/4469895/39271203-310f0f3c-488d-11e8-9891-248da6eb06d6.png)

My config files for multiple attempts:

`~/.config/ibus/rime/ibus_rime.yaml`:

```yaml
style:
  horizontal: true
```

`~/.config/ibus/rime/configibus_rime.yaml`:

```yaml
style:
  horizontal: true
```

`~/.config/ibus/rime/ibus_rime.custom.yaml` (didn't think this would work because there's no counterpart in `rime_data`, but still tried):

```yaml
patch:
  "style/horizontal": true
```

And I've deployed several times after these changes, but none of them worked. I wonder if I'm missing something?

**Comment by c0ldcat** [comment]
use '~/.config/ibus/rime/build/ibus_rime.yaml' temporarily

**Comment by lotem** [comment]
with the recent librime 1.3 update `RimeConfigOpen` no longer reads the original user copy of `*.yaml`. the config file only works with older librime now. I will fix this in the next patch release.

**Comment by DreaminginCodeZH** [comment]
As in a deleted comment, you can manually copy the file to `~/.config/ibus/rime/build/ibus_rime.yaml` to temporarily work around this. Worked for me well.

**Comment by lotem** [comment]
Fixed via https://github.com/rime/ibus-rime/commit/8e081264977bfefdd233ebeb1235f11be55b28f8

**Comment by AlynxZhou** [comment]
@lotem Currently I must modifiy `~/.config/ibus/rime/build/ibus_rime.yaml` to make it horizonal, but I think this is not correct because YAML under build might be changed by program, but adding patch in `~/.config/ibus/rime/ibus_rime.custom.yaml` does not work, can you fix this?

**Comment by AlynxZhou** [comment]
For example, if I modified `~/.config/ibus/rime/build/ibus_rime.yaml` with:
```
style:
  horizontal: true
```
it works as expected, but refer to your document, I should modify `~/.config/ibus/rime/ibus_rime.custom.yaml` instead, but I removed the former line in `~/.config/ibus/rime/build/ibus_rime.yaml` and added patch in `~/.config/ibus/rime/ibus_rime.custom.yaml`:
```
patch:
  style:
    horizontal: true
```
not work, this is different to document.

**Comment by lotem** [comment]
@AlynxZhou are you reporting the same issue described in https://github.com/rime/ibus-rime/issues/42#issue-317772118 ?
I've fixed this issue. https://github.com/rime/ibus-rime/issues/42#issuecomment-450477870
Do you have my fix in your build while you experienced the issue?

**Comment by AlynxZhou** [comment]
> @AlynxZhou are you reporting the same issue described in [#42 (comment)](https://github.com/rime/ibus-rime/issues/42#issue-317772118) ?
> I've fixed this issue. [#42 (comment)](https://github.com/rime/ibus-rime/issues/42#issuecomment-450477870)
> Do you have my fix in your build while you experienced the issue?
No, I don't think they are the same. Your fix seems only load `~/.config/ibus/rime/build/ibus_rime.yaml`, but not `~/.config/ibus/rime/ibus_rime.custom.yaml`, refers to your document it seems I should use the later. I am using 1.4.0 and it contains this fix.

**Comment by lotem** [comment]
Your settings go to `~/.config/ibus/rime/ibus_rime.yaml`, use the first code snippet in L1.

**Comment by AlynxZhou** [comment]
> Your settings go to `~/.config/ibus/rime/ibus_rime.yaml`, use the first code snippet in L1.

Thank you for your reply!

![](https://pic1.zhimg.com/v2-594ee8e4cf65e59cdf7299597463b9e0_r.jpeg)

However, this never works. Only modifying `build/ibus_rime.yaml` works, but this is not preferred by document.

Let me re-describe it. Referring to the document, if I want to patch a file like `build/<filename>.yaml`, I should use `<filename>.custom.yaml` out of the `build` dir, right? I can use `default.custom.yaml` to patch `build/default.yaml`, so I should be able to use `ibus_rime.custom.yaml` to patch `build/ibus_rime.yaml` here.

First thing we know is if I add
```
style:
  horizontal: true
```
to `build/ibus_rime.yaml`, all works as expected. But this is not good because rime may re-generate files under `build` dir, so I want to use a patch like what we do for `default.custom.yaml`. And if I am not wrong, I should remove the former config in `build/ibus_rime.yaml`, then add
```
patch:
  style:
    horizontal: true
```
to `ibus_rime.custom.yaml`. Then run `ibus-daemon -rdx`, it should add those patch to `build/ibus_rime.yaml`, and make ibus panel horizontal too. But it is not.

So I suggest to support patching `ibus_rime.yaml` in this way, this is the same as document, and so user does not need to touch `build` dir.

**Comment by AlynxZhou** [comment]
A wrong image is uploaded instead of my screenshot, sorry. Here is the screenshot.

![Screenshot from 2020-05-25 12-31-29](https://user-images.githubusercontent.com/8444615/82779060-bd2e7980-9e85-11ea-9670-b6dfd41212ce.png)

**Comment by lotem** [comment]
Never modify files in `build/`, those are auto-generated files based on your YAML configuration.

`*.custom.yaml` files are used to patch existing `*.yaml` or `*.schema.yaml` files that usually belong to the Rime distribution instead of the user. In your case you don't have an existing `ibus_rime.yaml`. Files in `build/` are the compiled version of YAML with patches applied, not the target of the patches.

**Comment by AlynxZhou** [comment]
> Never modify files in `build/`, those are auto-generated files based on your YAML configuration.
> 
> `*.custom.yaml` files are used to patch existing `*.yaml` or `*.schema.yaml` files that usually belong to the Rime distribution instead of the user. In your case you don't have an existing `ibus_rime.yaml`. Files in `build/` are the compiled version of YAML with patches applied, not the target of the patches.

OK, it works now, thank you.

**Comment by imyhxy** [comment]
@AlynxZhou I encounter the same problem, how do you make it work?

**Comment by AlynxZhou** [comment]
> @AlynxZhou I encounter the same problem, how do you make it work?

First create `~/.config/ibus/rime/ibus_rime.yaml` with following content:

```yaml
style:
  horizontal: true
```

then re-deploy it.

You can refer to my blog post for detailed reason if you read Chinese: <https://sh.alynx.one/posts/My-RIME/>.

**Comment by MakerFace** [comment]
> ibus-rime/jammy,now 1.5.0-1 amd64
> ubuntu 22.04

我发现如果新建了`ibus_rime.yaml`，当我`rm -f ~/.config/ibus/rime/build/`，执行`ibus-daemon -rdx`后，我新建的文件莫名其妙的就被删除了。所以我添加了`sudo chattr +i ~/.config/ibus/rime/ibus_rime.yaml`来防止被删除，希望可以解决！

**Comment by zxx-457** [comment]
> 
Arch linux

我也是， 被删除了放到trash了
trash/* - 失效的文件。因 Rime 升級而不再使用的舊文件會自動移入這個文件夾。用家確認不再需要後可以刪除。

**Comment by zxx-457** [comment]
> > ibus-rime/jammy,now 1.5.0-1 amd64
> > ubuntu 22.04
> 
> 我发现如果新建了`ibus_rime.yaml`，当我`rm -f ~/.config/ibus/rime/build/`，执行`ibus-daemon -rdx`后，我新建的文件莫名其妙的就被删除了。所以我添加了`sudo chattr +i ~/.config/ibus/rime/ibus_rime.yaml`来防止被删除，希望可以解决！

你用ibus_rime.custom.yaml 就可以配置了， 我一开也以为这个不写custom的

**Comment by Corgile** [comment]
新的问题，现在ibus_rime.custom.yaml中修改字号等主题相关的配置 并不生效
ibus, debian 12

**Comment by imyhxy** [comment]
@Corgile 什么字体这么好看

**Comment by Corgile** [comment]
> @Corgile 什么字体这么好看

nerdfont官网找的 叫 geist mono  按ctrl f 搜gei就找到了
