### ISSUE TITLE
Wrong candidates(luna_pinyin_simp) or no candidate(double_pinyin_flypy) with Ubuntu 18.04.2 LTS

### ISSUE THREAD

**Issue by jizusun** [rime/ibus-rime#65]
### Step to reproduce

My intention was to type out "测试", but  

- with `schema: double_pinyin_flypy`, no candidate at all

![double-pinyin-flyfy](https://user-images.githubusercontent.com/4011348/56403396-bbae7d00-6293-11e9-82fa-abf555554a85.png)

- with `schema: luna_pinyin_simp`, wrong candidates

![screenshot-pinyin](https://user-images.githubusercontent.com/4011348/56403391-b94c2300-6293-11e9-841b-2a176c904838.png)

### Versions

ibus version: 1.5.17-3ubuntu4
ibus-rime version: 1.2-1build2
Ubuntu version: 18.04.2 LTS

Can anyone else reproduce the problem or guide me?
Thanks so much!

**Comment by lotem** [comment]
Usually the phenomenon is caused by inconsistency between `*.prism.bin` and `*.table.bin` files.
It could be a result of incomplete deployment.
Please check logs in `/tmp/rime.ibus.INFO` after deploying data to see if any error has happened during the process.

**Comment by MonstreCharmant** [comment]
I've encountered the exact same error, please, how do I redeploy?

**Comment by lotem** [comment]
delete `*.bin` in `~/.config/ibus/rime/`
if manually installed files in`/usr/share/rime-data/`, also delete `*.bin` files there.
then follow https://github.com/rime/home/wiki/CustomizationGuide#%E9%87%8D%E6%96%B0%E4%BD%88%E7%BD%B2%E7%9A%84%E6%93%8D%E4%BD%9C%E6%96%B9%E6%B3%95

**Comment by jizusun** [comment]
> delete `*.bin` in `~/.config/ibus/rime/`
> if manually installed files in`/usr/share/rime-data/`, also delete `*.bin` files there.
> then follow https://github.com/rime/home/wiki/CustomizationGuide#%E9%87%8D%E6%96%B0%E4%BD%88%E7%BD%B2%E7%9A%84%E6%93%8D%E4%BD%9C%E6%96%B9%E6%B3%95

After deleting `*.bin` and another deployment, the issue is solved. 
Thanks @lotem

**Comment by jizusun** [comment]
> delete `*.bin` in `~/.config/ibus/rime/`
> if manually installed files in`/usr/share/rime-data/`, also delete `*.bin` files there.
> then follow https://github.com/rime/home/wiki/CustomizationGuide#%E9%87%8D%E6%96%B0%E4%BD%88%E7%BD%B2%E7%9A%84%E6%93%8D%E4%BD%9C%E6%96%B9%E6%B3%95

@lotem This issue happens again when I install `fcitx` and `fcitx-rime` on a new Ubuntu 18.04.
I spent almost an hour to investigate this issue before I recalled my issue here.

Can you explain a little more it why do I need to delete these files? 
I would like to write it somewhere in the rime wiki, maybe :smile: 


### I fix the issue by 
```
rm /usr/share/rime-data/*.bin
```
But actually I didn't **manually installed files**

### The logs:
```
jizu@ubuntu:/usr/share/rime-data$ cat /tmp/rime.fcitx-rime.ERROR 
Log file created at: 2020/03/30 16:23:11
Running on machine: ubuntu
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E0330 16:23:11.543650  3565 mapped_file.cc:112] attempt to open non-existent file '/home/jizu/.config/fcitx/rime/double_pinyin_flypy.prism.bin'.
E0330 16:23:11.543773  3565 prism.cc:83] error opening prism file '/home/jizu/.config/fcitx/rime/double_pinyin_flypy.prism.bin'.
E0330 16:23:11.543783  3565 dictionary.cc:270] Error loading prism for dictionary 'luna_pinyin'.
E0330 16:23:54.869089  3565 mapped_file.cc:112] attempt to open non-existent file '/home/jizu/.config/fcitx/rime/double_pinyin_flypy.prism.bin'.
E0330 16:23:54.869117  3565 prism.cc:83] error opening prism file '/home/jizu/.config/fcitx/rime/double_pinyin_flypy.prism.bin'.
E0330 16:23:54.869129  3565 dictionary.cc:270] Error loading prism for dictionary 'luna_pinyin'.

```

**Comment by lotem** [comment]
You can consider it a bug, but not necesarily a bug in librime.

It could be the data package that shipped mismatching .bin files. It could be that fcitx-rime didn't complete the initial deployment process. Anyway the bug is caused by bad/obsolete data files. That's why the issue goes away if you delete the .bin files and redo deploy. But it doesn't mean you are expected to do so.

I cannot tell you for sure why you experienced the bug. Nor do I have control in what you get from the Linux distribution: I suggested software packagers not to package binary data, yet they insisted because it is the way Linux software are distributed; fcitx-rime is made by other people, this is definitely not the same issue as in ibus-rime; also, the packaged version of librime in Ubuntu 18.04 is pretty old: 
Current version:
1.2.9+dfsg2-1
Uploaded:
2017-12-29
The built data files are in different forms now. It can be easily broken if any package is obsolete.

What I can do is making my best effort to make the lastest code in master work correctly if you follows the `make && make install` convention and also build data fresh.
