### ISSUE TITLE
Where is the running logs?

### ISSUE THREAD

**Issue by Honghe** [rime/ibus-rime#69]
Environment:
- Ubuntu 18.04
- ibus-rime 1.4.0

Sincerely!

**Comment by hchunhui** [comment]
@lotem
I think the issue(logs are missing) is introduced from [here](https://github.com/rime/ibus-rime/commit/6deef296e8f8f067b9bbc347187cbbc0dd871848#diff-a4c95e1d3b790d560ef54ed173f72fabL133).

The issue can be fixed by reverting the change. But it may not be the right way, since `RimeSetupLogging` is a "old" API.

**Comment by alswl** [comment]
`ls $TMPDIR/rime.*`

**Comment by lotem** [comment]
Fixed by https://github.com/rime/ibus-rime/commit/5ee34cbfbe31853b333c3399ba5e52c61b84edb5

**Comment by zhmars** [comment]
hi, I just got a notification: `See /tmp/rime.ibus.ERROR for details.`,  it was `ibus.ERROR` file actually.

**Comment by YaoLiMuMu** [comment]
i cant find rime runing logs(/temp, $TMPDIR) after I install librime and librime-lua, how can I enable it again. my device is ubuntu 20

**Comment by UlyssesZh** [comment]
Still has this problem

**Comment by lazyzyf** [comment]
I have this problem too.
